# Site settings
title: Jordan Levinson
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jordan Levinson
user_description: "I am a skilled professional in Enterprise Environments, with almost a decade of experience. Strong business forcus with a expertise varying from Hybrid Cloud Architechture, Automation, Network & Network Design, Virtualization, Cloud Security, Cryptography and much more. Bilingual communication skills in English and Spanish, I have a knack for understanding customer business requirements and crafting tailored solutions. I am now seeking opportunities to further my knowledge, grow personally, and embark on a new career path in Enterprise environments where I can continue my AI focused path, all while contributing to a great company.  
<br> 
<br> I'm Jordan V. Levinson, a seasoned network engineer and architect with a diverse range of skills and a passion for innovation. With extensive experience in network infrastructure, cloud security, virtualization, and communication technologies, I bring a holistic approach to solving complex problems. My ability to communicate effectively in both English and Spanish has proven invaluable in understanding clients' unique business requirements.
<br> 
<br> Professionally, I excel in designing, optimizing, and maintaining network infrastructures for businesses of all sizes. My expertise spans VeloCloud, Cisco, Fortigate, Meraki, Juniper, and cloud security solutions. What sets me apart is my knack for translating technical jargon into understandable language for clients, ensuring they get precisely what they need.
<br> 
<br> I'm not just looking for opportunities; I'm eager to contribute to an organization's growth while nurturing my AI-focused career path. My experience as a Senior Network Engineer V/Architect at Tetra Technologies involved managing and optimizing complex networks, leading projects, and ensuring security compliance.
<br> 
<br> During my tenure at GFI Digital, I collaborated closely with sales teams to design network and security solutions tailored to clients' business requirements. I also provided architectural network design expertise and delivered post-sales implementation, showcasing my ability to bridge the gap between technical and non-technical stakeholders.
<br> 
<br> At Dell Technologies, I acted as a technical escalation point and design/deployment specialist, working closely with customers to ensure their virtualized environments ran optimally. My role also involved troubleshooting complex issues, documenting solutions, and providing feedback for product improvements.
<br> 
<br> In summary, my expertise extends far beyond technical know-how; it's about delivering innovative solutions, fostering effective communication, and driving growth. I'm passionate about leveraging my skills to solve real-world challenges and contribute meaningfully to my field."
user_description1:
user_description2:
user_description3:
user_description4:
user_description5:
user_description6:
user_description7:
user_description8:
user_description9:
user_title: Senior Engineer / Architect
email: jvlevinson@yahoo.com
linkedin_username: jordanlevinson91
github_username:  jordanl91
# twitter_username: lorem_ipsum
#instagram_username: lorem_ipsum
#facebook_username: lorem_ipsum
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum
section_about: About
section_certs: Certifications
section_resume: Resume

exclude: ['package.json', 'src', 'node_modules', 'vendor']

nav_links:
  - name: "About"
    url: "about.html"  # Link to the About page
  - name: "Certifications"
    url: "certifications.html"  # Link to the Certifications page
  - name: "Letters"
    url: "letters.html"  # Link to the Letters page