# Site settings
title: Jordan Levinson
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jordan Levinson
user_description: I am a skilled professional in Enterprise Environments, with almost a decade of experience. Strong business forcus with a expertise varying from Hybrid Cloud Architechture, Automation, Network & Network Design, Virtualization, Cloud Security, Cryptography and much more. Bilingual communication skills in English and Spanish, I have a knack for understanding customer business requirements and crafting tailored solutions. I am now seeking opportunities to further my knowledge, grow personally, and embark on a new career path in Enterprise environments where I can continue my AI focused path, all while contributing to a great company.
user_title: Senior Engineer
email: jvlevinson@yahoo.com
linkedin_username: jordanlevinson91
github_username:  jordanl91
# twitter_username: lorem_ipsum
#instagram_username: lorem_ipsum
#facebook_username: lorem_ipsum
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About: "about"
  Certifications: "certifications"
  Letters: "letters"